name: Report an issue with Hubspace custom component
description: Report an issue with HACS plugin Hubspace
labels: ["bug", "triage"]
assignees:
  - Expl0dingBanana
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!
  - type: dropdown
    validations:
      required: true
    attributes:
      label: When did this issue occur?
      options:
        - New Issue
        - After Home Assistant Upgrade
        - After custom component upgrade
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue here.

        Provide a clear and concise description of what the problem is.
  - type: textarea
    validations:
      required: false
    attributes:
      label: Datadump
      description: >-
        Place to upload ``_dump_hs_devices.json`` which contains device information. Upload the
        file and not the contents of the file.
        [How to generate file](https://github.com/jdeath/Hubspace-Homeassistant?tab=readme-ov-file#troubleshooting) .
        This link does not open a new tab.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: What version of Home Assistant Core has the issue?
      placeholder: core-
      description: >
        Can be found in: [Settings ⇒ System ⇒ Repairs ⇒ Three Dots in Upper Right ⇒ System information](https://my.home-assistant.io/redirect/system_health/).

        [![Open your Home Assistant instance and show the system information.](https://my.home-assistant.io/badges/system_health.svg)](https://my.home-assistant.io/redirect/system_health/)
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What type of installation are you running?
      description: >
        Can be found in: [Settings ⇒ System ⇒ Repairs ⇒ Three Dots in Upper Right ⇒ System information](https://my.home-assistant.io/redirect/system_health/).

        [![Open your Home Assistant instance and show the system information.](https://my.home-assistant.io/badges/system_health.svg)](https://my.home-assistant.io/redirect/system_health/)
      options:
        - Home Assistant OS
        - Home Assistant Container
        - Home Assistant Supervised
        - Home Assistant Core
  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    attributes:
      label: Anything in the logs that might be useful for us?
      description: For example, error message, or stack traces.
      render: txt
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
