name: Report an issue with the Myko Integration
description: Myko is converting to Myko+, which is no longer supported by this integration
labels: ["bug", "triage"]
assignees:
  - Expl0dingBanana
body:
  - type: markdown
    attributes:
      value: |
        Myko is converting to Myko+ which is will be based on Tuya on or before Feburary 2026. Unfortunately this will not be a protocol we support but there are other integrations that support tuya. Please refer to https://github.com/jdeath/Hubspace-Homeassistant/issues/212.